baseurl: "https://gsdesign.ai/"
languageCode: en-us
title: gsDesign documentation for AI code editors
theme: hugo-gsdesign
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  blog: /blog/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: MCP Server (coming soon)
      url: "#"
      weight: 2

params:
  logo:
    alt: Logo
    height: 50
    url: images/logo.png
    width: 50
  googleAnalytics: ''
  description: 'Up-to-date documentation of clinical trial design and simulation packages for LLMs and AI coding tools'
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
