name = "Hugo gsDesign"
license = "MIT"
licenselink = "https://github.com/keaven/gsDesign/blob/main/LICENSE"
description = "A Hugo theme for gsDesign.ai"
homepage = "https://gsdesign.ai/"
tags = ["documentation", "ai", "clinical-trials", "statistics"]
features = ["tailwindcss", "responsive", "ai-optimized"]
min_version = "0.112.0"

[author]
  name = "gsDesign authors"
  homepage = "https://github.com/keaven/gsDesign"
