name = "Hugo gsDesign"
license = "MIT"
description = "A Hugo theme for gsDesign.ai"
homepage = "https://gsdesign.ai/"
tags = ["documentation", "ai", "clinical-trials", "statistics"]
features = ["tailwindcss", "responsive", "ai-optimized"]
min_version = "0.112.0"

[author]
  name = "gsDesign.ai authors"
  homepage = "https://github.com/nanxstats/gsdesign-ai"
